#pragma once

#include <cstddef>

namespace stellar::test {

// A single test entry.
//
// Convention used by this repo:
//  - test sources are named `test_*.cpp`
//  - each file defines a global `int test_xxx()` function that returns the number of failures
//
// The registry is generated by CMake at configure time.
struct Case {
  const char* name;
  int (*fn)();
};

// Returns a pointer to an internal (static) array of test cases and writes
// the element count to `outCount`.
const Case* cases(std::size_t* outCount);

} // namespace stellar::test
