#pragma once

#include "stellar/render/Shader.h"
#include "stellar/render/ShaderToyParams.h"
#include "stellar/render/Texture.h"

#include <string>
#include <string_view>

namespace stellar::render {

// ShaderToy-style fullscreen procedural shader runner.
//
// This utility is intentionally tiny and OpenGL 3.3 compatible:
//  - A fixed fullscreen-triangle vertex shader.
//  - A fragment shader generated by wrapping a user-provided snippet.
//
// User snippet contract (default wrapper):
//   - Must define: `vec4 shaderMain(vec2 uv);`
//   - uv is in [0,1] (origin lower-left in GL convention).
//   - A small standard library + uniforms are injected (see buildShaderToyFragmentSource()).
//
// This is used by the in-game Procedural Shader Lab to iterate on procedural
// generation shaders without rebuilding the application.

struct ShaderToyInputs {
  int width{1};
  int height{1};

  // ShaderToy-ish time base.
  float timeSec{0.0f};
  float timeDeltaSec{0.0f};
  int frame{0};

  // Multi-pass graphs can tag the currently rendered pass.
  // Convention in this project: 0..3 = Buffer A..D, 4 = Image.
  int passIndex{0};

  int seed{1};

  // iMouse: (x,y current) and (z,w click origin). Convention matches ShaderToy roughly.
  // Coordinates are in pixels, origin lower-left.
  float mouse[4]{0, 0, 0, 0};

  // Optional camera (useful for raymarching sketches).
  float camPos[3]{0, 0, 3};
  float camRight[3]{1, 0, 0};
  float camUp[3]{0, 1, 0};
  float camForward[3]{0, 0, -1};
  float tanHalfFovY{0.577350269f}; // tan(60/2 deg)
  float aspect{1.0f};

  // Optional textures for iChannel0..3 (ShaderToy convention).
  // If a channel is null, a 1x1 black texture will be bound.
  const Texture2D* channels[4]{nullptr, nullptr, nullptr, nullptr};

  // Optional user parameters (parsed from `// @param ...` directives).
  // These are applied as uniforms right before drawing.
  const ShaderToyParamSet* userParams{nullptr};
};

// Builds the full GLSL330 fragment shader by wrapping a user snippet.
// The wrapper injects a minimal library:
//  - integer-hash based value noise (2D/3D)
//  - fbm helpers
//  - Worley/Voronoi distance
//  - palette() helper
//  - sdSphere / sdBox for quick SDF sketches
//  - rayDirFromUv() for camera-based ray reconstruction
//
// It also injects a subset of ShaderToy uniforms:
//  - iResolution, iTime, iTimeDelta, iFrame, iMouse, iSeed, iPass
//  - iChannel0..3, iChannelResolution[4]
std::string buildShaderToyFragmentSource(std::string_view userCode, std::string_view extraHeader = {});

class ShaderToy {
public:
  ShaderToy() = default;
  ~ShaderToy();

  ShaderToy(const ShaderToy&) = delete;
  ShaderToy& operator=(const ShaderToy&) = delete;

  bool init(std::string* outError = nullptr);

  // Compile shader from a user snippet (see contract in file header).
  bool build(std::string_view userCode, std::string* outError = nullptr);

  // Compile shader from a user snippet plus extra wrapper header code.
  // Typically used to inject user parameter uniforms.
  bool buildWithHeader(std::string_view userCode, std::string_view extraHeader, std::string* outError = nullptr);

  // Draw to the currently bound framebuffer.
  void draw(const ShaderToyInputs& in) const;

  const std::string& lastVertexSource() const { return lastVertex_; }
  const std::string& lastFragmentSource() const { return lastFragment_; }

private:
  ShaderProgram shader_{};
  unsigned int vao_{0};

  // Default bound texture for unconnected channels.
  Texture2D blackTex_{};

  std::string lastVertex_{};
  std::string lastFragment_{};
};

} // namespace stellar::render
